fragment UserFields on User {
  id
  login
  avatarUrl
}

query searchUsers($query: String!) {
  result: search(query: $query, type: USER, first: 5) {
    edges {
      node {
        ...UserFields
      }
    }
  }
}
